# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d13625b1605e32ff2bebc15e331821ef96011d149a38e0ca5be55f57bc3c9a64fab4210eb4c96da3990c863f11a8e006053effedd5582003fdf7b1b6b72593c6

test:
  secret_key_base: d94125aa4c90a0d5b7fc2e9e03f8baa1b0e459bf81cce407a94bbbf697402755ba32f98e887e175556d9fea6b5e58536376a1db65a03610c008cb4734d8a7cbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
